<?xml version="1.0"?>
<package format="3">
  <name>aurora</name>
  <version>0.1.0</version>
  <description>Robot-specific SLAMTEC Aurora S integration and configuration.</description>
  <maintainer email="hw.jo@wego-robotics.com">juno</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>slamware_ros_sdk</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
