#!/usr/bin/env python3
"""검수고 점유격자 지도를 ROS map_server 형식(PGM + YAML)으로 만든다.

SLAM Toolbox 가 실제 현장에서 뽑아 올 지도를 대신하는 파일이다. 실물이
나오면 이 파일은 버리면 되고, 그때까지 관제 화면과 시뮬레이터가 실제와
비슷한 넓이·통로 구조 위에서 돌아가게 하는 것이 목적이다.

현장 가정
---------
- 검수고 안에 나란한 선로 두 개. 각 선로 위에 편성이 한 대씩 서 있다.
- 로봇(B2)은 차량 **아래**를 걸어서 지나간다. GTX-A 차량 바닥은 레일면에서
  1 m 넘게 떠 있어 사족보행 로봇이 통과할 수 있다. 그래서 피트를 파서
  그 안을 다니는 구조가 아니라, 검수고 바닥 위를 다니는 평면 하나로
  표현된다 — 2D 점유격자로 그릴 수 있는 것도 이 때문이다.
- 차량 아래에서 실제 장애물은 **대차(bogie)** 다. 레일은 낮아 라이다
  평면에 걸리지 않으므로 장애물로 넣지 않는다.
- 편성 사이 통로, 편성 옆 통로, 편성 양 끝의 횡통로로 돌아다닌다.

ROS 지도 규약
-------------
- PGM 값: 0(검정) = 점유, 254(흰색) = 자유, 205 = 미탐색
- YAML 의 origin 은 **좌하단** 셀의 월드 좌표. 이미지 0 행은 **맨 위** 행이라
  Y 축이 뒤집힌다.

사용법:
    python3 tools/make_depot_map.py gcs/resources/maps/gtxa_depot
"""

import sys
from pathlib import Path

# ---- 치수 (m) ----------------------------------------------------------
RES = 0.05                # m/cell — SLAM Toolbox 기본값

SHED_X, SHED_Y = 72.0, 24.0     # 검수고 내부 크기
WALL = 0.4                      # 벽 두께

TRACK_Y = 4.6                   # 선로 중심선 (±). 중심 간격 9.2 m
CAR_LEN = 20.0                  # GTX-A 1량 길이
CAR_N = 3                       # 지도에 들어오는 량 수
CAR_GAP = 0.6                   # 량 사이 간격
BODY_HALF = 1.55                # 차체 반폭 — 차량이 차지하는 평면 폭

BOGIE_LEN, BOGIE_HALF = 2.6, 1.1   # 대차 크기 (평면)
BOGIE_INSET = 2.6                  # 량 끝에서 대차 중심까지

PILLAR = 0.5              # 기둥 한 변
PILLAR_STEP = 12.0        # 기둥 간격

DOCK_X, DOCK_Y = 3.2, 2.4   # 충전 스테이션 외형

FREE, OCC, UNKNOWN = 254, 0, 205


class Grid:
    """월드 좌표(m)로 칠하는 격자. 원점은 지도 한가운데."""

    def __init__(self, w_m, h_m, res):
        self.res = res
        self.w = int(round(w_m / res))
        self.h = int(round(h_m / res))
        self.ox = -w_m / 2.0
        self.oy = -h_m / 2.0
        self.cells = bytearray([UNKNOWN]) * (self.w * self.h)

    def _col(self, x):
        return int(round((x - self.ox) / self.res))

    def _row(self, y):
        # 이미지 0 행이 맨 위. 월드 Y 는 위로 증가하므로 뒤집는다.
        return self.h - 1 - int(round((y - self.oy) / self.res))

    def rect(self, x0, y0, x1, y1, value):
        c0, c1 = sorted((self._col(x0), self._col(x1)))
        r0, r1 = sorted((self._row(y0), self._row(y1)))
        for r in range(max(0, r0), min(self.h, r1 + 1)):
            base = r * self.w
            for c in range(max(0, c0), min(self.w, c1 + 1)):
                self.cells[base + c] = value

    def frame(self, x0, y0, x1, y1, thickness, value):
        self.rect(x0, y0, x1, y0 + thickness, value)
        self.rect(x0, y1 - thickness, x1, y1, value)
        self.rect(x0, y0, x0 + thickness, y1, value)
        self.rect(x1 - thickness, y0, x1, y1, value)

    def write(self, stem: Path, map_id: str):
        pgm = stem.with_suffix(".pgm")
        header = f"P5\n# {map_id} - generated by tools/make_depot_map.py\n{self.w} {self.h}\n255\n"
        pgm.write_bytes(header.encode("ascii") + bytes(self.cells))

        stem.with_suffix(".yaml").write_text(
            f"image: {pgm.name}\n"
            f"resolution: {self.res}\n"
            f"origin: [{self.ox:.3f}, {self.oy:.3f}, 0.0]\n"
            f"negate: 0\n"
            f"occupied_thresh: 0.65\n"
            f"free_thresh: 0.196\n",
            encoding="ascii",
        )
        return pgm


def build(map_id: str) -> Grid:
    g = Grid(SHED_X + 2 * WALL + 1.0, SHED_Y + 2 * WALL + 1.0, RES)

    hx, hy = SHED_X / 2.0, SHED_Y / 2.0

    # 검수고 내부와 외벽
    g.rect(-hx, -hy, hx, hy, FREE)
    g.frame(-hx - WALL, -hy - WALL, hx + WALL, hy + WALL, WALL, OCC)

    # 편성 전체 길이와 시작점 — 지도 가운데에 놓는다
    train_len = CAR_N * CAR_LEN + (CAR_N - 1) * CAR_GAP
    x_start = -train_len / 2.0

    for sign in (+1, -1):
        ty = sign * TRACK_Y

        for car in range(CAR_N):
            cx0 = x_start + car * (CAR_LEN + CAR_GAP)
            cx1 = cx0 + CAR_LEN

            # 대차 두 개. 차체 자체는 머리 위로 지나가므로 바닥 평면에서는
            # 장애물이 아니다 — 로봇이 그 아래로 걸어 들어간다.
            for bx in (cx0 + BOGIE_INSET, cx1 - BOGIE_INSET):
                g.rect(bx - BOGIE_LEN / 2, ty - BOGIE_HALF,
                       bx + BOGIE_LEN / 2, ty + BOGIE_HALF, OCC)

            # 량과 량 사이 연결부. 아래로 지나갈 수 없어 막힌 것으로 둔다.
            if car < CAR_N - 1:
                g.rect(cx1, ty - BODY_HALF * 0.5,
                       cx1 + CAR_GAP, ty + BODY_HALF * 0.5, OCC)

    # 검수고 기둥. 편성 옆 통로에 규칙적으로 선다.
    x = -hx + PILLAR_STEP / 2
    while x < hx:
        for py in (hy - 1.4, -hy + 1.4):
            g.rect(x - PILLAR / 2, py - PILLAR / 2,
                   x + PILLAR / 2, py + PILLAR / 2, OCC)
        x += PILLAR_STEP

    # 충전 스테이션 — 편성 끝 너머 횡통로 구석. 안쪽은 로봇이 들어가야
    # 하므로 비워 둔다.
    dx0, dy0 = -hx + 1.0, -hy + 1.0
    g.rect(dx0, dy0, dx0 + DOCK_X, dy0 + DOCK_Y, OCC)
    g.rect(dx0 + 0.3, dy0 + 0.3, dx0 + DOCK_X - 0.3, dy0 + DOCK_Y, FREE)

    # 벽면 검수 설비함
    for x in (-hx + 14.0, -hx + 30.0, -hx + 46.0):
        g.rect(x, hy - 1.0, x + 2.2, hy, OCC)

    return g


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    stem = Path(sys.argv[1])
    stem.parent.mkdir(parents=True, exist_ok=True)
    g = build(stem.name)
    pgm = g.write(stem, stem.name)

    occ = sum(1 for v in g.cells if v == OCC)
    free = sum(1 for v in g.cells if v == FREE)
    print(f"{pgm}  {g.w}×{g.h} cells  "
          f"{g.w * RES:.1f}×{g.h * RES:.1f} m  "
          f"자유 {free * 100 // len(g.cells)}%  점유 {occ * 100 // len(g.cells)}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
