#pragma once

// Drawable geometry for the 3D pose view, loaded from resources/robot_mesh.bin.
//
// The blob is generated by tools/make_robot_mesh.py from the same models the
// robot is simulated and trained with - Unitree's MJCF for B2, FAIRINO's URDF
// meshes for the FR3 - reduced to about 16 000 triangles by vertex clustering.
// It is binary rather than a generated header because that many triangles of
// C++ initialiser is roughly 700 KB of source that no one can review and every
// incremental build pays for.
//
// FORMAT (little-endian)
// ---------------------
//   char[8]   "B2MSH2\0\0"
//   float32   base_height   B2 base_link above the ground, standing
//   float32[3] arm_mount    where the FR3 bolts on, in base_link coordinates
//   uint32    part_count
//   per part:
//     uint16  name length, then that many bytes, not terminated
//     uint8   group   0 B2 body, 1 B2 leg, 2 FR3 link
//     uint8   reserved
//     uint32  vertex count, then 3 float32 each
//     uint32  triangle count, then 3 uint32 each
//     then 9 float32 per triangle: a unit normal for each of its three corners
//
// B2 parts carry vertices already posed in base_link coordinates with the legs
// at the FixStand posture, because the protocol carries no quadruped joint
// feedback to animate them. FR3 parts are in their own joint frames and appear
// in chain order, so part i is placed by joint frame i of
// hmi::robot::jointFrames().

#include <QString>
#include <QVector3D>

#include <vector>

namespace hmi::ui::mesh {

struct Tri {
    quint32 a, b, c;
};

/// Per-corner normals, one set per triangle.
///
/// Shading a triangle by its own normal makes every facet a distinct plane,
/// and the robot reads as chiselled rather than moulded - visibly unlike the
/// same model in MuJoCo. Averaging normals across the flat edges and keeping
/// them apart across the sharp ones fixes that. They are stored per corner
/// rather than per vertex because a vertex sitting on a crease needs a
/// different normal on each side of it.
struct TriNormals {
    QVector3D a, b, c;
};

struct Part {
    QString name;
    int group = 0;  ///< 0 B2 body, 1 B2 leg, 2 FR3 link
    std::vector<QVector3D> vertices;
    std::vector<Tri> faces;
    std::vector<TriNormals> normals;  ///< same length as `faces`
};

struct Model {
    float baseHeight = 0.0f;
    QVector3D armMount;
    std::vector<Part> b2;   ///< posed, drawn as one rigid body
    std::vector<Part> fr3;  ///< chain order: base, shoulder, upperarm, forearm, wrist 1-3

    bool isEmpty() const { return b2.empty() && fr3.empty(); }
    int faceCount() const;
};

/// Reads the blob once and returns the same model on every later call.
///
/// A parse failure returns an empty model rather than throwing: the 3D view is
/// one panel of a control station, and losing the picture of the arm must not
/// take the screen that shows whether the robot is stopped. The view draws a
/// message in that case, and the failure is logged once.
const Model &model();

}  // namespace hmi::ui::mesh
